# Copyright (C) 2023-2024 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: rotation_estimation
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - numpy
  - scipy
  - pytorch
  - pre-commit
  - flake8
  - opencv-python-headless
  - matplotlib
  - tqdm
